### ISSUE TITLE
"Exception: HTTP Error 400: Bad Request" at login

### ISSUE THREAD

**Issue by hgcvm** [gabrielreid/polar-flow-export#3]
I'm getting this error when trying the script:

>INFO:PolarFlowExporter:Logging in user usernam@email.com
ERROR:PolarFlowExporter:Error fetching https://flow.polar.com/login: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "polarflowexport.py", line 158, in <module>
    for tcx_file in exporter.get_tcx_files(from_date_str, to_date_str):
  File "polarflowexport.py", line 114, in get_tcx_files
    self._login()
  File "polarflowexport.py", line 101, in _login
    email=self._username, password=self._password))
  File "polarflowexport.py", line 92, in _execute_request
    raise Exception(e)
Exception: HTTP Error 400: Bad Request`

**Comment by hgcvm** [comment]
I found the reason why. I had a "$" in my password.
